# Generated by Django 2.0.2 on 2019-01-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upwd', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=11, null=True, unique=True)),
                ('userName', models.CharField(max_length=100, null=True)),
                ('userEmail', models.CharField(max_length=30, null=True, unique=True)),
                ('userAddress', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
