# Generated by Django 2.0.2 on 2019-01-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfor',
            name='photo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
